name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    # Install dependencies for backend
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install

    # Install dependencies for frontend
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install

    # Build the frontend
    - name: Build frontend
      working-directory: ./frontend
      run: npm run build

    # Run backend tests (if you have any)
    - name: Run backend tests
      working-directory: ./backend
      run: npm test

    # Run frontend tests (if you have any)
    - name: Run frontend tests
      working-directory: ./frontend
      run: npm test
